import { useMemo, useState } from 'react'
import type { ChildProfile, CompletionMap } from '../types'
import { localDateKey } from '../lib/persistence'
type Props={profile:ChildProfile;completionDays:Record<string,CompletionMap>;onSelectDate:(date:string)=>void;onBack:()=>void}
export function ChildCalendar({profile,completionDays,onSelectDate,onBack}:Props){
 const [cursor,setCursor]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)}),today=localDateKey()
 const days=useMemo(()=>{const first=new Date(cursor.getFullYear(),cursor.getMonth(),1),last=new Date(cursor.getFullYear(),cursor.getMonth()+1,0);const out:(Date|null)[]=Array(first.getDay()).fill(null);for(let n=1;n<=last.getDate();n++)out.push(new Date(cursor.getFullYear(),cursor.getMonth(),n));return out},[cursor])
 return <main className="calendar-screen"><header className="calendar-header"><button className="mini-profile" onClick={onBack}>{profile.photoDataUrl?<img src={profile.photoDataUrl} alt=""/>:<span>{profile.emoji}</span>}</button><div><p className="calendar-eyebrow">Choose a day</p><h1>{profile.name}'s Calendar</h1></div></header><section className="calendar-card"><div className="calendar-nav"><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}>‹</button><h2>{cursor.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}>›</button></div><div className="calendar-weekdays">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><span key={x}>{x}</span>)}</div><div className="calendar-grid">{days.map((d,i)=>{if(!d)return <span key={'e'+i}/>;const key=localDateKey(d),done=Object.keys(completionDays[key]??{}).length,isToday=key===today,isFuture=key>today,isPast=key<today,total=(profile.activities??[]).filter(a=>a.enabled!==false&&(!a.days?.length||a.days.includes(d.getDay()))).length,pending=Math.max(0,total-done);return <button key={key} className={'calendar-day '+(isToday?'is-today ':'')+(done?'has-done ':'')+(isFuture?'is-future':'')} onClick={()=>onSelectDate(key)}><strong>{d.getDate()}</strong>{isToday&&<small>Today</small>}{done>0&&<span>✓ {done}</span>}{isToday&&pending>0&&<span>⏳ {pending}</span>}{isPast&&pending>0&&<span>○ {pending}</span>}</button>})}</div></section></main>
}
