-- Project Kavleen web MVP
-- Stores one completion per child/activity/day for the currently authenticated browser user.
-- Enable Anonymous Sign-Ins in Supabase Auth for browser-to-Supabase sync.

create table if not exists public.daily_activity_completions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  child_key text not null,
  activity_key text not null,
  activity_date date not null,
  completed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (owner_id, child_key, activity_key, activity_date)
);

alter table public.daily_activity_completions enable row level security;

drop policy if exists "Users can read own activity completions"
  on public.daily_activity_completions;

create policy "Users can read own activity completions"
  on public.daily_activity_completions
  for select
  to authenticated
  using ((select auth.uid()) = owner_id);

drop policy if exists "Users can insert own activity completions"
  on public.daily_activity_completions;

create policy "Users can insert own activity completions"
  on public.daily_activity_completions
  for insert
  to authenticated
  with check ((select auth.uid()) = owner_id);

drop policy if exists "Users can update own activity completions"
  on public.daily_activity_completions;

create policy "Users can update own activity completions"
  on public.daily_activity_completions
  for update
  to authenticated
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);
